services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - auth-network
    restart: unless-stopped
    mem_limit: 50m

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    expose:
      - "8080"
    env_file:
      - .env.prod
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - ENV=production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - auth-network
    restart: unless-stopped
    mem_limit: 100m

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=authuser
      - POSTGRES_PASSWORD=authpassword
      - POSTGRES_DB=authdb
      - POSTGRES_SHARED_PRELOAD_LIBRARIES=""
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth-network
    restart: unless-stopped
    mem_limit: 200m
    command: postgres -c shared_buffers=32MB -c effective_cache_size=128MB

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - auth-network
    restart: unless-stopped
    mem_limit: 50m
    command: redis-server --maxmemory 32mb --maxmemory-policy allkeys-lru

volumes:
  postgres_data:
  redis_data:

networks:
  auth-network:
    driver: bridge