# Kubernetes Secrets for Production
apiVersion: v1
kind: Secret
metadata:
  name: auth-system-secrets
  namespace: default
type: Opaque
stringData:
  JWT_SECRET: "your-production-jwt-secret-key"
  DB_PASSWORD: "your-production-db-password"
  REDIS_PASSWORD: "your-production-redis-password"
  SMTP_PASS: "your-production-smtp-password"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-system
  template:
    metadata:
      labels:
        app: auth-system
    spec:
      containers:
      - name: auth-app
        image: flack74/go-auth-system:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: DB_HOST
          value: "postgres-service"
        - name: REDIS_HOST
          value: "redis-service"
        envFrom:
        - secretRef:
            name: auth-system-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"