name: Docker Build

on:
  schedule:
    - cron: '0 2 * * 0'  # Weekly rebuild
  workflow_dispatch:     # Manual trigger

env:
  IMAGE_NAME: flack74/go-auth-system

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build multi-platform image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile
        platforms: ${{ matrix.platform }}
        push: true
        tags: ${{ env.IMAGE_NAME }}:nightly
        cache-from: type=gha
        cache-to: type=gha,mode=max