name: Release

on:
  push:
    tags:
      - 'v*'

env:
  IMAGE_NAME: flack74/go-auth-system

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Run tests
      run: go test -v ./...
      env:
        JWT_SECRET: test-secret-key
        BCRYPT_COST: 4
    
    - name: Build binaries
      run: |
        GOOS=linux GOARCH=amd64 go build -o auth-linux-amd64 ./cmd/api
        GOOS=darwin GOARCH=amd64 go build -o auth-darwin-amd64 ./cmd/api
        GOOS=windows GOARCH=amd64 go build -o auth-windows-amd64.exe ./cmd/api
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push release image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          ${{ env.IMAGE_NAME }}:stable
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          auth-linux-amd64
          auth-darwin-amd64
          auth-windows-amd64.exe
        generate_release_notes: true